// Generated by CoffeeScript 1.9.3
(function() {
  var Game, V2, V2Polar;

  V2 = (function() {
    function V2(x1, y1) {
      this.x = x1;
      this.y = y1;
    }

    V2.prototype.plus = function(arg) {
      var x, y;
      x = arg.x, y = arg.y;
      return new V2(this.x + x, this.y + y);
    };

    V2.prototype.minus = function(arg) {
      var x, y;
      x = arg.x, y = arg.y;
      return new V2(this.x - x, this.y - y);
    };

    V2.prototype.times = function(arg) {
      var x, y;
      x = arg.x, y = arg.y;
      return new V2(this.x * x, this.y * y);
    };

    V2.prototype.distance = function(arg) {
      var x, y;
      x = arg.x, y = arg.y;
      return Math.sqrt(Math.pow(this.x - x, 2) + Math.pow(this.y - y, 2));
    };

    V2.prototype.magnitude = function() {
      return this.distance(new V2(0, 0));
    };

    V2.prototype.angle = function() {
      return Math.atan2(this.y, this.x);
    };

    V2.prototype.withMagnitude = function(r) {
      return V2Polar(r, this.angle());
    };

    V2.prototype.withAngle = function(theta) {
      return V2Polar(this.magnitude(), theta);
    };

    return V2;

  })();

  V2Polar = function(r, theta) {
    return new V2(r * Math.cos(theta), r * Math.sin(theta));
  };

  Game = (function() {
    function Game(canvas1) {
      this.canvas = canvas1;
    }

    Game.prototype.tick = function() {};

    Game.prototype.draw = function() {};

    Game.prototype.mousedown = function(v2) {};

    Game.prototype.mouseup = function(v2) {};

    Game.prototype.mousemove = function(v2) {};

    return Game;

  })();

  $(document).ready(function() {
    var canvas, gameLoop, handle, resize;
    canvas = $('#the-canvas')[0];
    window.game = new Game(canvas);
    handle = function(mouseEvent) {
      return function(e) {
        var left, ref, top;
        ref = $('#the-canvas').offset(), left = ref.left, top = ref.top;
        return window.game[mouseEvent](new V2(e.pageX - left, e.pageY - top));
      };
    };
    $('#the-canvas').mousedown(handle('mousedown'));
    $(document).mousemove(handle('mousemove'));
    $(document).mouseup(handle('mouseup'));
    resize = function() {
      canvas.width = $(window).width();
      return canvas.height = $(window).height();
    };
    resize();
    $(window).resize(function() {
      return resize();
    });
    return (gameLoop = function() {
      window.game.tick();
      window.game.draw();
      return requestAnimationFrame(gameLoop);
    })();
  });

}).call(this);
