// Generated by CoffeeScript 1.9.3
(function() {
  var Chokecherries, allReady, drawCenter, oneReady, readies, sashaAfterCooking, sashaBeforeStep1, sashaBeforeStep2, sashaBeforeStep3;

  sashaBeforeStep1 = 29449;

  sashaBeforeStep2 = 33976;

  sashaBeforeStep3 = 33978;

  sashaAfterCooking = 28522;

  drawCenter = function(layer, image) {
    var h, imageRatio, layerRatio, w, x, y;
    layerRatio = layer.width / layer.height;
    imageRatio = image.width / image.height;
    if (layerRatio < imageRatio) {
      w = layer.width;
      h = layer.width / imageRatio;
    } else {
      w = imageRatio * layer.height;
      h = layer.height;
    }
    x = (layer.width - w) / 2;
    y = (layer.height - h) / 2;
    return layer.drawImage(image, x, y, w, h);
  };

  Chokecherries = {
    create: function() {
      return this.stage = 0;
    },
    step: function() {},
    render: function() {
      this.app.layer.clear('white');
      return drawCenter(this.app.layer, this.app.images["chokecherries-" + (Math.min(this.stage, 4))]);
    },
    pointerdown: function(e) {
      var ref, ref1;
      if ((ref = this.stage) === 0) {
        return this.stage++;
      } else if ((ref1 = this.stage) === 1 || ref1 === 2 || ref1 === 3) {
        this.app.sound.play('squish');
        return this.stage++;
      } else if (this.stage === 4) {
        return window.ARIS.exitToDialog(sashaAfterCooking);
      }
    }
  };

  allReady = function() {
    return window.game = playground({
      create: function() {
        var i, j;
        for (i = j = 0; j <= 4; i = ++j) {
          this.loadImage("chokecherries-" + i + ".png");
        }
        return this.loadSounds('squish');
      },
      ready: function() {
        return this.setState(Chokecherries);
      }
    });
  };

  readies = 2;

  oneReady = function() {
    readies--;
    if (readies === 0) {
      return allReady();
    }
  };

  window.ARIS = {
    ready: oneReady
  };

  document.addEventListener('DOMContentLoaded', oneReady);

}).call(this);
