// Generated by CoffeeScript 1.9.3
(function() {
  var allReady, drawCenter, i, imgs, len, loadImage, loadImages, oneReady, readies, ref, s, sashaBeforeStep1, sashaBeforeStep2, sashaBeforeStep3, sashaBeforeStep4, sashaEnd, sounds, steps;

  sashaBeforeStep1 = 29449;

  sashaBeforeStep2 = 33976;

  sashaBeforeStep3 = 33978;

  sashaBeforeStep4 = 53383;

  sashaEnd = 28522;

  drawCenter = function(canvas, ctx, image) {
    var h, imageRatio, layerRatio, w, x, y;
    layerRatio = canvas.width / canvas.height;
    imageRatio = image.width / image.height;
    if (layerRatio < imageRatio) {
      w = canvas.width;
      h = canvas.width / imageRatio;
    } else {
      w = imageRatio * canvas.height;
      h = canvas.height;
    }
    x = (canvas.width - w) / 2;
    y = (canvas.height - h) / 2;
    return ctx.drawImage(image, x, y, w, h);
  };

  loadImage = function(src, cb) {
    var img;
    img = new Image;
    img.onload = function() {
      return cb(img);
    };
    return img.src = src;
  };

  sounds = {};

  steps = [
    {
      image: "plating-1.jpg"
    }, {
      image: "plating-2.jpg",
      sound: 'squish'
    }, {
      image: "plating-3.jpg",
      sound: 'squish'
    }, {
      image: "plating-4.jpg",
      sound: 'slap'
    }, {
      image: "plating-5.jpg",
      sound: 'snap'
    }, {
      image: "plating-6.jpg",
      sound: 'snap'
    }, {
      image: "plating-7.jpg",
      sound: 'snap'
    }, {
      image: "plating-8.jpg",
      sound: 'snap'
    }, {
      image: "plating-9.jpg",
      sound: 'snap'
    }, {
      image: "plating-10.jpg",
      sound: 'snap'
    }, {
      image: "plating-11.jpg",
      sound: 'snap'
    }, {
      image: "plating-12.jpg",
      sound: 'snap'
    }
  ];

  imgs = {};

  loadImages = function(cb) {
    var count, fn, i, image, len;
    count = steps.length;
    fn = function(image) {
      return loadImage("images/" + image, function(img) {
        imgs[image] = img;
        count--;
        if (count === 0) {
          return cb();
        }
      });
    };
    for (i = 0, len = steps.length; i < len; i++) {
      image = steps[i].image;
      fn(image);
    }
    return void 0;
  };

  allReady = function() {
    var canvas, clickListener, ctx, nextStep, step;
    canvas = document.getElementById('the-canvas');
    ctx = canvas.getContext('2d');
    clickListener = null;
    step = -1;
    nextStep = function() {
      var image, ref, sound;
      step++;
      if (steps[step] != null) {
        ref = steps[step], image = ref.image, sound = ref.sound;
        canvas.width = window.innerWidth;
        canvas.height = window.innerHeight;
        ctx.fillStyle = 'white';
        ctx.fillRect(0, 0, canvas.width, canvas.height);
        if (image != null) {
          drawCenter(canvas, ctx, imgs[image]);
        }
        if (sound != null) {
          return sounds[sound].play();
        }
      } else {
        return window.ARIS.exitToDialog(sashaEnd);
      }
    };
    canvas.addEventListener('touchstart', nextStep);
    Origami.fastclick(document.body);
    return loadImages(nextStep);
  };

  readies = 5;

  oneReady = function() {
    readies--;
    if (readies === 0) {
      return allReady();
    }
  };

  window.ARIS = {
    ready: oneReady
  };

  document.addEventListener('DOMContentLoaded', oneReady);

  ref = ['squish', 'slap', 'snap'];
  for (i = 0, len = ref.length; i < len; i++) {
    s = ref[i];
    sounds[s] = new Howl({
      src: ["sounds/" + s + ".ogg", "sounds/" + s + ".mp3"],
      onload: oneReady
    });
  }

}).call(this);
