// Generated by CoffeeScript 1.9.3
(function() {
  var Bison, allReady, drawCenter, oneReady, readies, sashaAfterCooking, sashaBeforeStep1, sashaBeforeStep2, sashaBeforeStep3;

  sashaBeforeStep1 = 29449;

  sashaBeforeStep2 = 33976;

  sashaBeforeStep3 = 33978;

  sashaAfterCooking = 28522;

  drawCenter = function(layer, image) {
    var h, imageRatio, layerRatio, w, x, y;
    layerRatio = layer.width / layer.height;
    imageRatio = image.width / image.height;
    if (layerRatio < imageRatio) {
      w = layer.width;
      h = layer.width / imageRatio;
    } else {
      w = imageRatio * layer.height;
      h = layer.height;
    }
    x = (layer.width - w) / 2;
    y = (layer.height - h) / 2;
    return layer.drawImage(image, x, y, w, h);
  };

  Bison = {
    create: function() {
      return this.stage = 0;
    },
    step: function() {
      if (this.stage <= 6) {
        return null;
      } else {
        return window.ARIS.exitToDialog(sashaBeforeStep3);
      }
    },
    render: function() {
      this.app.layer.clear('white');
      return drawCenter(this.app.layer, this.app.images["bison-" + (Math.min(this.stage, 6))]);
    },
    pointerdown: function(e) {
      var ref, ref1;
      if ((ref = this.stage) === 0 || ref === 1 || ref === 2 || ref === 3 || ref === 6) {
        if (this.stage === 0) {
          this.app.sound.play('fwoosh');
        }
        if (this.stage === 1) {
          this.app.sound.play('ting');
        }
        if (this.stage === 2) {
          this.app.sound.play('slap');
        }
        if (this.stage === 3) {
          this.app.sound.play('sizzle');
        }
        return this.stage++;
      } else if ((ref1 = this.stage) === 4 || ref1 === 5) {
        this.app.sound.play('slap');
        return this.stage++;
      }
    }
  };

  allReady = function() {
    return window.game = playground({
      create: function() {
        var i, j;
        for (i = j = 0; j <= 6; i = ++j) {
          this.loadImage("bison-" + i + ".png");
        }
        return this.loadSounds('fwoosh', 'ting', 'slap', 'sizzle');
      },
      ready: function() {
        return this.setState(Bison);
      }
    });
  };

  readies = 2;

  oneReady = function() {
    readies--;
    if (readies === 0) {
      return allReady();
    }
  };

  window.ARIS = {
    ready: oneReady
  };

  document.addEventListener('DOMContentLoaded', oneReady);

}).call(this);
