// Generated by CoffeeScript 1.9.3
(function() {
  var Spinner, allReady, dialogDallasEnd, inRect, oneReady, readies, wordMap,
    modulo = function(a, b) { return (+a % (b = +b) + b) % b; };

  dialogDallasEnd = 47262;

  wordMap = [
    {
      Happy: 59806,
      "Caŋteŝica (Sad)": 59807,
      Calm: 59810
    }, {
      Creative: 59812,
      Confused: 59813,
      Surprised: 59815
    }, {
      Curious: 59817,
      "Waŝte (Good)": 59819,
      Excited: 59822
    }
  ];

  inRect = function(rect, x, y) {
    return ((rect.x <= x && x <= rect.x + rect.w)) && ((rect.y <= y && y <= rect.y + rect.h));
  };

  Spinner = {
    create: function() {
      var column, word;
      this.columns = [0, 0, 0];
      this.pointerInfo = null;
      return this.words = (function() {
        var j, len, results;
        results = [];
        for (j = 0, len = wordMap.length; j < len; j++) {
          column = wordMap[j];
          results.push((function() {
            var results1;
            results1 = [];
            for (word in column) {
              results1.push(word);
            }
            return results1;
          })());
        }
        return results;
      })();
    },
    step: function() {},
    getDims: function() {
      var colWidth;
      colWidth = (this.app.layer.width - 10) / 3;
      return {
        column0: {
          x: 5,
          y: 5,
          w: colWidth,
          h: this.app.layer.height - 10
        },
        column1: {
          x: 5 + colWidth,
          y: 5,
          w: colWidth,
          h: this.app.layer.height - 10
        },
        column2: {
          x: 5 + colWidth + colWidth,
          y: 5,
          w: colWidth,
          h: this.app.layer.height - 10
        },
        row: {
          w: this.app.layer.width - 10,
          h: (this.app.layer.height - 10) / 3
        }
      };
    },
    render: function() {
      var c, col, dims, fillColors, i, j, k, l, len, len1, len2, len3, len4, len5, lines, m, n, o, r, ref, ref1, ref2, ref3, ref4, ref5, repeat, rowOffset, y;
      dims = this.getDims();
      this.app.layer.clear('black');
      this.app.layer.globalAlpha(1);
      this.app.layer.strokeStyle('black');
      this.app.layer.lineWidth(7);
      fillColors = ['#48b', '#8b4', '#b58'];
      ref = [dims.column0, dims.column1, dims.column2];
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        col = ref[i];
        this.app.layer.fillStyle(fillColors[i]);
        this.app.layer.fillRect(col.x, col.y, col.w, col.h);
        this.app.layer.strokeRect(col.x, col.y, col.w, col.h);
      }
      this.app.layer.lineWidth(1);
      ref1 = [0, 1, 2];
      for (k = 0, len1 = ref1.length; k < len1; k++) {
        r = ref1[k];
        col = dims["column" + r];
        rowOffset = this.columns[r] % 1;
        ref2 = [0, 1, 2];
        for (l = 0, len2 = ref2.length; l < len2; l++) {
          i = ref2[l];
          y = col.y + (i + rowOffset) * dims.row.h;
          this.app.layer.strokeLine(col.x, y, col.x + col.w, y);
        }
      }
      this.app.layer.textAlign('center');
      this.app.layer.textBaseline('middle');
      this.app.layer.fillStyle('black');
      this.app.layer.font((this.app.layer.height / 11) + "px sans-serif");
      ref3 = [0, 1, 2];
      for (m = 0, len3 = ref3.length; m < len3; m++) {
        c = ref3[m];
        col = dims["column" + c];
        ref4 = [0, 1, 2];
        for (n = 0, len4 = ref4.length; n < len4; n++) {
          r = ref4[n];
          y = col.y + col.h / 2 + (this.columns[c] + r) * dims.row.h;
          ref5 = [-2, -1, 0];
          for (o = 0, len5 = ref5.length; o < len5; o++) {
            repeat = ref5[o];
            lines = this.words[c][r].split(/\s+/);
            if (lines.length === 2) {
              this.app.layer.fillText(lines[0], col.x + col.w / 2, y + dims.column1.h * repeat - this.app.layer.height / 16);
              this.app.layer.fillText(lines[1], col.x + col.w / 2, y + dims.column1.h * repeat + this.app.layer.height / 16);
            } else {
              this.app.layer.fillText(lines[0], col.x + col.w / 2, y + dims.column1.h * repeat);
            }
          }
        }
      }
      this.app.layer.fillStyle('black');
      this.app.layer.globalAlpha(0.3);
      this.app.layer.fillRect(dims.column0.x, dims.column0.y, dims.row.w, dims.row.h);
      return this.app.layer.fillRect(dims.column0.x, dims.column0.y + 2 * dims.row.h, dims.row.w, dims.row.h);
    },
    getWords: function() {
      var c, j, len, ref, results;
      ref = [0, 1, 2];
      results = [];
      for (j = 0, len = ref.length; j < len; j++) {
        c = ref[j];
        results.push(this.words[c][modulo(-this.columns[c], 3)]);
      }
      return results;
    },
    roundAll: function() {
      var c, j, len, ref, results;
      ref = [0, 1, 2];
      results = [];
      for (j = 0, len = ref.length; j < len; j++) {
        c = ref[j];
        results.push(this.columns[c] = modulo(Math.round(this.columns[c]), 3));
      }
      return results;
    },
    pointerdown: function(arg) {
      var column, dims, x, y;
      x = arg.x, y = arg.y;
      if (!((x != null) && (y != null))) {
        return;
      }
      this.roundAll();
      dims = this.getDims();
      if (inRect(dims.column0, x, y)) {
        column = 0;
      } else if (inRect(dims.column1, x, y)) {
        column = 1;
      } else if (inRect(dims.column2, x, y)) {
        column = 2;
      } else {
        return;
      }
      this.pointerInfo = {
        y: y,
        column: column,
        started: this.columns[column]
      };
      return this.pointermove({
        x: x,
        y: y
      });
    },
    pointerup: function(arg) {
      var x, y;
      x = arg.x, y = arg.y;
      if (!((x != null) && (y != null))) {
        return;
      }
      if (this.pointerInfo == null) {
        return;
      }
      this.pointermove({
        x: x,
        y: y
      });
      this.roundAll();
      return this.pointerInfo = null;
    },
    pointermove: function(arg) {
      var x, y;
      x = arg.x, y = arg.y;
      if (!((x != null) && (y != null))) {
        return;
      }
      if (this.pointerInfo == null) {
        return;
      }
      return this.columns[this.pointerInfo.column] = modulo(this.pointerInfo.started + (y - this.pointerInfo.y) / this.getDims().row.h, 3);
    },
    submit: function() {
      var i, j, len, possibleWord, ref, word, wordItem, words;
      words = this.getWords();
      for (i = j = 0, len = words.length; j < len; i = ++j) {
        word = words[i];
        ref = wordMap[i];
        for (possibleWord in ref) {
          wordItem = ref[possibleWord];
          if (word === possibleWord) {
            ARIS.givePlayerItemCount(wordItem, 1);
          }
        }
      }
      return ARIS.exitToDialog(dialogDallasEnd);
    }
  };

  allReady = function() {
    return window.game = playground({
      create: function() {},
      ready: function() {
        return this.setState(Spinner);
      },
      container: document.getElementById('the-table')
    });
  };

  readies = 2;

  oneReady = function() {
    readies--;
    if (readies === 0) {
      return allReady();
    }
  };

  window.ARIS = {
    ready: oneReady
  };

  document.addEventListener('DOMContentLoaded', oneReady);

}).call(this);
